### ISSUE TITLE
Group Policy Section Failing

### ISSUE THREAD

**Issue by CyberneticRelay** [dakhama-mehdi/Modern_ActiveDirectory#2]
When running Powershell 7.3.3 on Windows with RSAT for group policy installed the group policy module doesn't show up under the get-modules command despite it being available on the system.  Could we possibly shift this to a try / catch operation instead?

**Comment by dakhama-mehdi** [comment]
Hello, Thanks you for reply, i will fix it. 
Is the result show the GPO details on report ?

**Comment by dakhama-mehdi** [comment]
Hi, 
I fix the problems by skiping check module GPO and AD for PS 7.X, because check capability requier privilege, pls update version and retry, it will be work, let me know

Update-version ModernActivedirectory
