### ISSUE TITLE
Error returned on Get-GPO

### ISSUE THREAD

**Issue by ylyony** [dakhama-mehdi/Modern_ActiveDirectory#4]
![Capture](https://user-images.githubusercontent.com/10506710/228527180-a182bed7-4335-4a51-9b50-fa8e954997ec.PNG)
As we shown on the capture, I've an error when I launch Get-AdModernReport
How can I track and correct that ?

**Comment by dakhama-mehdi** [comment]
For advance track : 

if (!$nogpomod) {
			$LinkedGPOs.Add((Get-GPO -Guid $Split2 -ErrorAction Stop -Errorvariable GPOTrack).DisplayName)
                       write-host $GPOTrack
        }
