### ISSUE TITLE
Suggestions et améliorations

### ISSUE THREAD

**Issue by Rapidhands** [dakhama-mehdi/Modern_ActiveDirectory#5]
Salut medhi, 
Joli report. 
Quelques points d'attention : 

- "Objects in DefaultOu" devrait être DefaultContainer (Users et Computersne sont pas des OUs).
- Account created in 7days or less : Cela remonte également les trusts (style Domaine$), le filtre est à revoir. 
- Users in Default OU : cela ne remonte pas que les users mais aussi les trusts. Les trusts sont des objets type user, ils sont cachés dans Users&Computers. Il faut modifier ton filtre ou les faire apparaitre ailleurs.
- Organisational Units : Cela ne fait apparaitre que les OU à la racine du domaine. Cela peut être un choix ...ou pas. Impec cependant la vue de synthèse sur "Protected from accidental deletion". 
- GPO : tu pourrais ajouter les GPO qui ont des LogonScripts. Cela est intéressant quand tu as une palanquée de GPOs. J'ai cela dans un des mes rapports sur les GPOs. 
- Printer server ; c'est vide (normal pas de printer dans mon domaine de test).Mais est-ce que tu vas bien chercher le ou les serveurs du domaine qui ont le rôle "Print Services" ? Si oui, RAS.
- USERS : cela remonte encore les trusts.

Sinon très jolie la présentation. Une dernière suggestion : Ajoute dans chaque section la possibilité de "collapse"la dite section (ex. New-HTMLSection -CanCollapse $true"
Olivier

**Comment by dakhama-mehdi** [comment]
Salut Olivier,
ca fait plaisir de te lire, oh tu m'as donné un devoir, alors je vais répondre sur les points déja traité.
* Pour les OU : par défaut je liste que ceux de base, on c'est jamais y'a trop dans une infra, mais y'a un parametre pour voir les différents niveaux 
OUlevelSearch / Search level in OUs (Base/Onelevel/Subtree)
*Pour les Printers on liste les serveurs ayant le role PrintServer et intégrée dans l'AD, sinon s'ils sont en workgroup je ne fais pas de winrm.

*Pour les OUs par défaut, je n'ai pas trop amélioré cette partie, à revoir elle se trouve au début si t'as une idée d'ici là, j'integrerai

**Comment by Rapidhands** [comment]
je n'avais pas vu le param permettant la recherche dans les sous-OUs. Ok donc. 
Pour les PrintServeur tu as parfaitement répondu et je fais pareil : query AD "donnes-moi la liste de serveurs  qui ont le rôle PrintServer" et là, je passe à la suite. 

OU par Défaut : Quand tu fais un Get-ADdomain, tu as 2 propriétés : UserContainer et ComputerContainer. Ce sont respectivement là que sont créés les users/computers quand on ne précise pas d'OU lors de la création. Cela peut se changer bien entendu  (avec redirusr et redircmp) pour aller pointer sur une "vraie" OU. Users et Computers ne sont pas des OUs mais des containers (regarde le DN / OU).
C'est le libellé "OU par défaut" qui peut poser question. Si cela a été changé (et c'est loin d'être le plus souvent le cas), ce sont bien des OUs. Sinon, ce sont des containers. Il faudrait utiliser un autre libellé peut-être., mais c'est plus du détail. 
Quoi que : imaginons. Si UserContainer <> Users (on a alors affaire à une "vraie" OU ==> Titre OU par défaut, sinon "Container par défaut". 
On peut faire de la mise en forme conditonnelle avec PSWriteHTML. (voir New-TableReplace)

**Comment by dakhama-mehdi** [comment]
Je sais bien que les OU par défaut sont des conteneurs, mais les autres contributeurs ont souhaité mettre OU default users et computers, c'est plus parlant pour la plupart des gens, figure toi y'a pas mal de personne qui sera embrouillé s'il entent conteneur computers. mais je vais essayer de proposer quelque chose de plus compréhensible.

**Comment by dakhama-mehdi** [comment]
Salut, merci pour ton retour, j'ai corrigé les OUs affichés, j'avais inversé la variable protected avec linked, merci beaucoup pour cette remarque, il faut faire un update la version 1.3.1 règle se problème.
Par contre dans le conteneur par défaut apart lister les users non activés je ne vois pas comment skiper les krbtgt et ceux par défaut  que tu appelles Trust.
si t'as une partie à améliorer n'hesite pas de pousser un RP ou de partager la partie de code ici, je l'intégrerai.

**Comment by Rapidhands** [comment]
Les trust (relation d’appro), apparaissent ou plutôt sont cachés dans le container Users et sont de type User. Chose intéressante, leur nom se termine pas un $ comme pour les machines (j’en ai près de 200 alors j’ai identifié à quoi cela correspondait). Pour les filtrer *$ (tout ce qui se termine par un $). Si tu utilises Get-Aduser, juste cela. Si tu utilises Get-ADObject pas oublier le filtre type User.    Envoyé à partir de Courrier pour Windows De : Dakhama mehdiEnvoyé le :dimanche 2 avril 2023 12:41À : dakhama-mehdi/Modern_ActiveDirectoryCc : Rapidhands; AuthorObjet :Re: [dakhama-mehdi/Modern_ActiveDirectory] Suggestions et améliorations (Issue #5) Salut, merci pour ton retour, j'ai corrigé les OUs affichés, j'avais inversé la variable protected avec linked, merci beaucoup pour cette remarque, il faut faire un update la version 1.3.1 règle se problème.Par contre dans le conteneur par défaut apart lister les users non activés je ne vois pas comment skiper les krbtgt et ceux par défaut que tu appelles Trust.si t'as une partie à améliorer n'hesite pas de pousser un RP ou de partager la partie de code ici, je l'intégrerai.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Rapidhands** [comment]
KRBTGT è SID https://morgantechspace.com/2013/10/well-known-sids-and-built-in-groups.html  Envoyé à partir de Courrier pour Windows De : Dakhama mehdiEnvoyé le :dimanche 2 avril 2023 12:41À : dakhama-mehdi/Modern_ActiveDirectoryCc : Rapidhands; AuthorObjet :Re: [dakhama-mehdi/Modern_ActiveDirectory] Suggestions et améliorations (Issue #5) Salut, merci pour ton retour, j'ai corrigé les OUs affichés, j'avais inversé la variable protected avec linked, merci beaucoup pour cette remarque, il faut faire un update la version 1.3.1 règle se problème.Par contre dans le conteneur par défaut apart lister les users non activés je ne vois pas comment skiper les krbtgt et ceux par défaut que tu appelles Trust.si t'as une partie à améliorer n'hesite pas de pousser un RP ou de partager la partie de code ici, je l'intégrerai.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Rapidhands** [comment]
[image: image.png]
Un exemple


Le dim. 2 avr. 2023 à 21:05, Olivier FERRIERE ***@***.***> a
écrit :

**Comment by dakhama-mehdi** [comment]
Salut olivier,
je vois rien, les liens ainsi que les rpéonses sont pas bien lisible. mais je vais ignorer quelque SID dans le filter defaultOU

**Comment by Rapidhands** [comment]
bonjour Khirtah
Pour VMWare et autres, je t'engage à te tourner vers [ASbuildReport](https://github.com/AsBuiltReport). C'est puissant, customisable à souhait (différents niveau de détails), export dans différents formats ...

**Comment by khirtah** [comment]
> bonjour Khirtah Pour VMWare et autres, je t'engage à te tourner vers [ASbuildReport](https://github.com/AsBuiltReport). C'est puissant, customisable à souhait (différents niveau de détails), export dans différents formats ...

Merci beaucoup pour le retour.
