### ISSUE TITLE
Erreur dans les variables

### ISSUE THREAD

**Issue by Rapidhands** [dakhama-mehdi/Modern_ActiveDirectory#7]
Graphique organizational Units Protected from Deletion
Protected :17
NotProtected 14
J'ai 17 aussi, toutes Protected (j'ai vérifié). Tu as du prendre une variable qui n'est pas la bonne quelque part. 

Idem pour le graphique OU with GPO Linked, cela ne reflète pas la réalité. J'ai toujours 17 OUs et elles n'ont pas toutes une GPO associée.

**Comment by Rapidhands** [comment]
après investigation, cela ne m'étonne pas. 
```
Get-ADObject -Filter { isDeleted -eq $true -and (ObjectClass -eq 'user' -or ObjectClass -eq 'computer' -or ObjectClass -eq 'group') } -IncludeDeletedObjects -Properties ObjectClass, whenChanged | ForEach-Object {
	
        if ($_.ObjectClass -eq 'GroupPolicyContainer')
        {
		
            $Name = $_.DisplayName
        }
...
```
Comment veux tu que cela donne le résultat attendu ? Comment peut-on trouver un ObjectClass = GroupPolicyContainer quand on a filtré juste avant sur User, computer et group ? 
A mon sens tu fais trop compliqué pour collecter les infos et du coup, tu te mélanges les pinceaux. Je te donne un exemple : 

```
# Initialisation
$GroupDeleted = $UserDeleted = $ComputerDeleted = $GPODeleted = $DeletedObjects = $TrustDeleted = $OUDeleted = $null


$DateMaxDeletedObject = (Get-Date).AddDays(-60) # j'ai mis cela pour avoir un peu de data
$DeletedObjects = Get-ADObject -Filter { isDeleted -eq $true } -IncludeDeletedObjects -Properties ObjectClass, whenChanged |
    Where-Object -Property whenChanged -GE $DateMaxDeletedObject |
    Select-Object -Property Name, ObjectClass, WhenChanged, DistinguishedName
# tu noteras que je n'ai filtré que sur "IsDeleted" et rien d'autres

# Pour pouvoir tester un foreach est bien plus intéressant qu'un foreach-Object. Après les test, libre à toi de passer à un foreach-object ou pas.
foreach ($Item in $DeletedObjects) 
{
# Je remplace les multiples if, ilseif, par un switch
    switch ($Item.ObjectClass)
    {
        'Group'
        {
            $GroupDeleted++ # Ca matche, on incrémente la variable
        }
        'User'
        {
            $UserDeleted++ 
        }
        'Computer'
        {
            $ComputerDeleted++ 
        }
        'OrganizationalUnit'
        {
            $OUDeleted++
        }
        'TrustedDomain'
        {
            $TrustDeleted++ 
        }
        'GroupPolicyContainer'
        {
            $GPODeleted++ 
        }
        Default
        {
        }
    }
}
# Building a PSObject
$TableDeletedObjects = [PSCustomObject] @{ 
    'Group'                = $GroupDeleted
    'User'                 = $UserDeleted
    'Computer'             = $ComputerDeleted
    'OrganizationalUnit'   = $OUDeleted
    'TrustDomain'        = $TrustDeleted
    'GroupPolicyContainer' = $GPODeleted
}
$TableDeletedObjects
```
Maintenant la table on en fait ce qu'on veut. On peut l'afficher sous forme de tableau, ou en faire un joli graphique. C'est un Objet, avec des propriétés.

**Comment by dakhama-mehdi** [comment]
Salut olivier,
Je pense que tu t'es trompé sur la partie OU, le code ne correspond pas à cette partie, y'a un bloc region OU, dans lequel on traire la partie protected not protected, ainsi que les GPOs liés.

```
Get-ADOrganizationalUnit -Filter * -Properties ProtectedFromAccidentalDeletion,whenchanged -SearchScope OneLevel | ForEach-Object {	
	$LinkedGPOs = New-Object 'System.Collections.Generic.List[System.Object]'	
	if (($_.linkedgrouppolicyobjects).length -lt 1)
	{		
		$LinkedGPOs = "None"
		$OUwithnoLink++
	} 	
	else
	{		
		$OUwithLinked++
		$GPOslinks = $_.linkedgrouppolicyobjects
		
		foreach ($GPOlink in $GPOslinks)
		{
			
			$Split1 = $GPOlink -split "{" | Select-Object -Last 1
			$Split2 = $Split1 -split "}" | Select-Object -First 1
            if (!$nogpomod) {
			$LinkedGPOs.Add((Get-GPO -Guid $Split2 -ErrorAction SilentlyContinue).DisplayName)
        }
		}
	}
	if ($_.ProtectedFromAccidentalDeletion -eq $True)
	{		
		$OUProtected++
	}	
	else
	{		
		$OUNotProtected++
	}	
```

**Comment by dakhama-mehdi** [comment]
et je viens de checker chez des clients, le nombre de protected et bel et bien correct, ainsi que celui des GPOs linked

**Comment by dakhama-mehdi** [comment]
Salut,

J'ai fait une correction sur le code pour ajouter les GPOs, je sais pas pourquoi je l'ai zappé, j'essaies d'implémenter ta méthode avec switch, mais n'oublies pas que je cherche aussi le nom de l'objet pour l'afficher, pas juste une incrémentation, et le switch ne permet pas de faire cela en une seule ligne, vu que tu rentre avec objectclass, si t'as une idée, je suis entrain de voir de mon coté.

**Comment by dakhama-mehdi** [comment]
J'ai corrigé cela, dans la nouvelle version 1.3.1 en attendant d'autres remontées ou améliorations

**Comment by Rapidhands** [comment]
Switch ($Var.param)                X { # do this}              Y { «  do that} Envoyé à partir de Courrier pour Windows De : Dakhama mehdiEnvoyé le :dimanche 2 avril 2023 11:27À : dakhama-mehdi/Modern_ActiveDirectoryCc : Rapidhands; AuthorObjet :Re: [dakhama-mehdi/Modern_ActiveDirectory] Erreur dans les variables (Issue #7) Salut,J'ai fait une correction sur le code pour ajouter les GPOs, je sais pas pourquoi je l'ai zappé, j'essaies d'implémenter ta méthode avec switch, mais n'oublies pas que je cherche aussi le nom de l'objet pour l'afficher, pas juste une incrémentation, et le switch ne permet pas de faire cela en une seule ligne, vu que tu rentre avec objectclass, si t'as une idée, je suis entrain de voir de mon coté.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
