### ISSUE TITLE
Created Machines / Users By date in last 30 Days data not in chronological order

### ISSUE THREAD

**Issue by YohanRodriguezMDM** [dakhama-mehdi/Modern_ActiveDirectory#8]
Here is the "Created Machines / Users By date in last 30 Days" graph for my domain, as you can see, dates are not displayed in chronological order.

I still not watched the code but I'm pretty sure it's a quick fix :)

![image](https://user-images.githubusercontent.com/71087699/231504094-296a9279-7992-40bb-bc23-c69d1e008f2a.png)

BTW, thanks for this module, it's awesome !

**Comment by dakhama-mehdi** [comment]
Hello, 
you have a reason, it's order on pscustomobject not sorted by date, i will fix it as soon.

**Comment by dakhama-mehdi** [comment]
Hi,
Problem is fixed by using sort date in new version, 1.3.2.
Pls use : 
Update-Module Modernactivedirectory 

and tell me know

**Comment by YohanRodriguezMDM** [comment]
It works perfectly, thanks :)
